source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 7.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

gem "rack-cors"
gem "devise"
gem "devise-jwt"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end
